name: Build Windows Executable

on:
  workflow_dispatch: # Allows you to manually trigger the build whenever you want

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run PyInstaller
      run: |
        pyinstaller --onefile --noconsole --collect-all markitdown app.py

    - name: Upload Finished Exe
      uses: actions/upload-artifact@v4
      with:
        name: MarkItDown-Windows-App
        path: dist/app.exe